defmodule IslandsEngine.GameServerTest do
  use ExUnit.Case, async: true
  alias IslandsEngine.{Coordinate,GameServer}

  test "a full game walk through" do
    {:ok, game} = GameServer.start_link("Allie")
    :ok = GameServer.join(game, "Jim")
    :ok = GameServer.position_island(game, "Allie", :dot, Coordinate.new!(2,1))
    :ok = GameServer.position_island(game, "Allie", :atoll, Coordinate.new!(1,1))
    :ok = GameServer.position_island(game, "Allie", :square, Coordinate.new!(4,1))
    :ok = GameServer.position_island(game, "Allie", :l_shape, Coordinate.new!(6,1))
    :ok = GameServer.position_island(game, "Allie", :s_shape, Coordinate.new!(1,3))
    :ok = GameServer.set_islands(game, "Allie")
    :ok = GameServer.position_island(game, "Jim", :dot, Coordinate.new!(2,1))
    :ok = GameServer.position_island(game, "Jim", :atoll, Coordinate.new!(1,1))
    :ok = GameServer.position_island(game, "Jim", :square, Coordinate.new!(4,1))
    :ok = GameServer.position_island(game, "Jim", :l_shape, Coordinate.new!(6,1))
    :ok = GameServer.position_island(game, "Jim", :s_shape, Coordinate.new!(1,3))
    :ok = GameServer.set_islands(game, "Jim")
    {:ok, :hit, :dot, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(2,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(1,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(1,2))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(3,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(2,2))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :atoll, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(3,2))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(4,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(4,2))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(5,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :square, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(5,2))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(6,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(7,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(8,1))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :l_shape, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(8,2))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(1,3))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(2,3))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :none, :no_win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(3,3))
    {:ok, :miss, :none, :no_win} = GameServer.guess_coordinate(game, "Jim", Coordinate.new!(9,9))
    {:ok, :hit, :s_shape, :win} = GameServer.guess_coordinate(game, "Allie", Coordinate.new!(3,4))
  end
end
